"""Generate short, audited PRIME LoRA SFT configurations."""

from __future__ import annotations

import json
import math
import re
import tomllib
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from .artifacts import ArtifactError, publish_bytes, publish_json, read_json, sha256_file
from .config import Campaign
from .prime_data import PRIME_DATASET_SCHEMA

TRAIN_PLAN_SCHEMA = "harness-posttrain.train-plan.v1"


def _quoted(value: str | Path) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _array(values: list[str]) -> str:
    return "[\n" + "".join(f"  {_quoted(value)},\n" for value in values) + "]"


def _smoke_targets(path: str | Path, campaign: Campaign) -> tuple[Path, list[str], str]:
    report = read_json(path)
    if not isinstance(report, dict) or report.get("status") != "ok":
        raise ArtifactError("model smoke report is not successful")
    if report.get("snapshot", {}).get("model_id") != campaign.model["model_id"]:
        raise ArtifactError("model smoke report identity drifted")
    snapshot = Path(str(report.get("resolved_snapshot", ""))).resolve()
    if not snapshot.is_dir():
        raise ArtifactError("smoke-tested snapshot is absent")
    targets = report.get("target_selection", {}).get("targets")
    if not isinstance(targets, list) or not targets or len(targets) != len(set(targets)):
        raise ArtifactError("smoke report has invalid LoRA targets")
    patterns = [f"^{re.escape(str(name))}$" for name in targets]
    return snapshot, patterns, str(report.get("snapshot", {}).get("revision", ""))


def _training_toml(
    *,
    stage: str,
    model: Path,
    dataset: Path,
    output: Path,
    target_patterns: list[str],
    settings: Mapping[str, Any],
    seed: int,
    num_gpus: int,
) -> bytes:
    updates = int(settings["optimizer_updates"])
    warmup_steps = min(updates - 1, max(1, math.ceil(updates * float(settings["warmup_fraction"]))))
    checkpoints = list(settings["checkpoint_updates"])
    interval = math.gcd(*checkpoints)
    lines = [
        "# PRIME-RL 0.7.0; generated by harness-posttrain",
        f"# stage = {stage}",
        f"# predeclared_candidate_updates = {checkpoints}",
        f"max_steps = {updates}",
        f"output_dir = {_quoted(output)}",
        "clean_output_dir = false",
        'matmul_precision = "high"',
        'loss_impl = "liger_fused"',
        "",
        "[env_vars]",
        'FLA_TILELANG = "0"',
        'WANDB_MODE = "disabled"',
        "",
        "[deployment]",
        'type = "single_node"',
        f"num_gpus = {num_gpus}",
        f"gpus_per_node = {num_gpus}",
        "",
        "[model]",
        f"name = {_quoted(model)}",
        f"seq_len = {int(settings['sequence_length'])}",
        'impl = "hf"',
        'attn = "flash_attention_2"',
        'optimization_dtype = "bfloat16"',
        'reduce_dtype = "bfloat16"',
        "cp = 2",
        'cp_style = "ulysses"',
        "",
        "[model.ac]",
        'mode = "full"',
        "freq = 1",
        "",
        "[model.lora]",
        f"rank = {int(settings['lora_rank'])}",
        f"alpha = {float(settings['lora_alpha'])}",
        f"dropout = {float(settings['lora_dropout'])}",
        f"target_modules = {_array(target_patterns)}",
        "modules_to_save = []",
        "",
        "[renderer]",
        'name = "qwen3.5"',
        "enable_thinking = true",
        "",
        "[data]",
        'type = "sft"',
        f"name = {_quoted(dataset)}",
        f"batch_size = {int(settings['global_batch_size'])}",
        f"seq_len = {int(settings['sequence_length'])}",
        "micro_batch_size = 1",
        'pack_function = "cat"',
        "shuffle = true",
        f"seed = {seed}",
        "",
        "[data.loss_mask]",
        "system = false",
        "user = false",
        "assistant = true",
        "tool = false",
        "",
        "[optim]",
        'type = "adamw"',
        f"lr = {float(settings['learning_rate'])}",
        "weight_decay = 0.01",
        f"max_norm = {float(settings.get('maximum_gradient_norm', 1.0))}",
        "",
        "[scheduler]",
        'type = "cosine"',
        f"warmup_steps = {warmup_steps}",
        "min_lr = 0.0",
        "",
        "[ckpt]",
        f"interval = {interval}",
        "resume_step = -1",
        "keep_last = 10",
        "",
        "[ckpt.weights]",
        "save_sharded = true",
        'save_format = "safetensors"',
        "save_adapter_separately = true",
    ]
    payload = ("\n".join(lines).rstrip() + "\n").encode()
    try:
        parsed = tomllib.loads(payload.decode())
    except tomllib.TOMLDecodeError as exc:
        raise ArtifactError("generated PRIME SFT TOML is invalid") from exc
    if parsed["data"]["loss_mask"] != {
        "system": False,
        "user": False,
        "assistant": True,
        "tool": False,
    }:
        raise AssertionError("assistant-only loss drifted")
    return payload


def generate_sft_configs(
    campaign: Campaign,
    *,
    stage: str,
    candidate: str | None = None,
    smoke_report: str | Path,
    parent_model: str | Path,
    dataset_dir: str | Path,
    output_dir: str | Path,
    num_gpus: int = 8,
) -> dict[str, Any]:
    if stage not in {"targeted_sft", "refinement"}:
        raise ArtifactError("stage must be targeted_sft or refinement")
    if num_gpus not in {4, 8}:
        raise ArtifactError("reviewed training topology requires four or eight GPUs")
    if stage == "targeted_sft" and num_gpus != 8:
        raise ArtifactError("targeted SFT topology requires one complete eight-GPU node")
    smoke_snapshot, targets, smoke_revision = _smoke_targets(smoke_report, campaign)
    parent = Path(parent_model).resolve()
    if not parent.is_dir():
        raise ArtifactError("parent model directory is absent")
    if stage == "targeted_sft" and parent != smoke_snapshot:
        raise ArtifactError("targeted SFT must initialize from the exact smoke-tested base")
    if stage == "refinement":
        provenance_path = parent / "merge_provenance.json"
        if not provenance_path.is_file() or not (parent / "config.json").is_file():
            raise ArtifactError("refinement parent must be an attested complete merged checkpoint")
        provenance = read_json(provenance_path)
        if (
            not isinstance(provenance, dict)
            or provenance.get("status") != "ok"
            or Path(str(provenance.get("output_dir", ""))).resolve() != parent
            or provenance.get("snapshot", {}).get("model_id") != campaign.model["model_id"]
            or provenance.get("snapshot", {}).get("revision") != campaign.model["revision"]
            or not provenance.get("logit_metrics")
        ):
            raise ArtifactError("refinement parent merge provenance is absent or incompatible")
    dataset = Path(dataset_dir).resolve()
    manifest = read_json(dataset / "manifest.json")
    if (
        not isinstance(manifest, dict)
        or manifest.get("schema") != PRIME_DATASET_SCHEMA
        or manifest.get("stage") != stage
        or manifest.get("campaign_digest") != campaign.digest
        or manifest.get("model_revision") != campaign.model["revision"]
        or (stage == "targeted_sft" and manifest.get("candidate") != candidate)
        or not (dataset / "train.parquet").is_file()
        or manifest.get("parquet_sha256") != sha256_file(dataset / "train.parquet")
    ):
        raise ArtifactError("PRIME dataset manifest is absent, incompatible, or drifted")
    if smoke_revision and smoke_revision != campaign.model["revision"]:
        raise ArtifactError("smoke revision differs from pinned model revision")
    if stage == "targeted_sft":
        if candidate is None:
            raise ArtifactError("targeted SFT config requires a candidate name")
        settings = campaign.targeted_sft_candidate(candidate)
    else:
        if candidate is not None:
            raise ArtifactError("refinement config cannot name a targeted SFT candidate")
        settings = campaign.campaign[stage]
    audit = manifest.get("token_audit", {})
    if audit.get("seq_len") != settings["sequence_length"] or audit.get(
        "global_batch_size"
    ) != settings["global_batch_size"]:
        raise ArtifactError("dataset token audit differs from the training configuration")
    output = Path(output_dir).resolve()
    training_output = output / "prime_output"
    payload = _training_toml(
        stage=stage,
        model=parent,
        dataset=dataset,
        output=training_output,
        target_patterns=targets,
        settings=settings,
        seed=int(campaign.campaign["seed"]) + (0 if stage == "targeted_sft" else 1),
        num_gpus=num_gpus,
    )
    config_name = candidate or stage
    config_path = publish_bytes(output / f"{config_name}.toml", payload)
    candidates = [
        {
            "update": update,
            "adapter": str(training_output / f"weights/step_{update}/lora_adapters"),
        }
        for update in settings["checkpoint_updates"]
    ]
    plan = {
        "schema": TRAIN_PLAN_SCHEMA,
        "stage": stage,
        "candidate": candidate,
        "campaign_digest": campaign.digest,
        "model": str(parent),
        "model_revision": campaign.model["revision"],
        "smoke_report_sha256": sha256_file(smoke_report),
        "dataset": str(dataset),
        "dataset_manifest_sha256": sha256_file(dataset / "manifest.json"),
        "config": str(config_path),
        "config_sha256": sha256_file(config_path),
        "optimizer_updates": settings["optimizer_updates"],
        "candidates": candidates,
        "selection_fallback": "retain_parent_if_no_candidate_passes",
    }
    publish_json(output / "plan.json", plan)
    return plan
